### ISSUE TITLE
API - filter unreachable points

### ISSUE THREAD

**Issue by jmarceli** [mapnificent/mapnificent#14]
Hi,
First of all very interesting project, something that I was looking for when trying to solve the issue of reachability in my town.

Is there any API for this service? I would like to have some function which will filter out all unreachable points from given points set. Maybe this is something that I should implement myself?

I'm looking for a function/endpoint which will do the following:
INPUT: center point map coordinates, other points (which I would like to check reachability for)
OUTPUT: other points - reachable (ideally with travel time), other points - unreachable

As far as I understand if I want to use the mapnificient in my app I should host it on my own?

**Comment by stefanw** [comment]
There will likely not be an API (everything is static, computation happens in the browser). But there will be a JS library extracted from the current code that allows generating GeoJSON shapes which will make filtering easy. I have a prototype working and will publish it soon.

**Comment by jmarceli** [comment]
If you do then I will be happy to test it (maybe I'll be able to help somehow).
