### ISSUE TITLE
Some data in Montreal seems to be wrong (too short of commute times)

### ISSUE THREAD

**Issue by joshlemer** [mapnificent/mapnificent#16]
Check this link https://www.mapnificent.net/montreal/#11/45.5924/-73.5713/2040/45.5182/-73.5952  

Note that the map indicates that one can travel [this route](https://www.google.ca/maps/dir/45.6400667,-73.4907152/397+Boulevard+Saint+Joseph+O,+Montr%C3%A9al,+QC+H2V+2P1,+Canada/@45.5674408,-73.58427,12.22z/data=!4m9!4m8!1m0!1m5!1m1!1s0x4cc91a2a95dadc47:0xd16aeb8ce22a49ef!2m2!1d-73.5954514!2d45.5182766!3e3) in less than 34 minutes.

**Comment by stefanw** [comment]
I can confirm this is a problem. Stations have been merged that are way to far apart. I will look into this.

**Comment by stefanw** [comment]
This has been fixed in mapnificent_generator v0.0.3 and an update of Montreal is now live. Other cities will be updated soon.
