### ISSUE TITLE
Supporting rail transport for London?

### ISSUE THREAD

**Issue by jucor** [mapnificent/mapnificent#19]
Hi!

Brilliant tool :) What would be the steps to add  rail connexions for London, please? Indeed, many Londoners commute  from nearby villages (St Albans, Hitchins), which are within 30-40 minutes from Kings Cross by train, and Mapnificent is completely oblivious to that possibility.

Thanks for any help!

**Comment by stefanw** [comment]
Hi! First step would be to locate the data free of charge and the second step would be to find a GTFS (transit data standard) version of it or convert existing data to that standard. The incorporated TfL data is converted from the UK transit data standard as well.

**Comment by jucor** [comment]
Thanks Stefan ! I'll search for GTFS or UK TransferXchange (and a
converter), then, and report here. It must exist somewhere, as Mapumental
has it.

**Comment by stefanw** [comment]
@jucor Any news on this?

**Comment by stefanw** [comment]
I added data from [ATOC](http://transitfeeds.com/p/association-of-train-operating-companies/284) to Mapnificent Londn and Mapnificent Manchester. Please let me know if this fixes the coverage.
