### ISSUE TITLE
Not working for Zurich

### ISSUE THREAD

**Issue by lidiamcfreitas** [mapnificent/mapnificent#21]
Problem: Mapnificent isn't working for the city of Zürich

Description:
Mapnificent website not working for the city of Zürich. Wherever you drop the pin the result doesn't change and only shows circle around pin, doesn't take into account any data. (See picture)

Picture:
<img width="390" alt="screenshot 2018-08-20 08 51 49" src="https://user-images.githubusercontent.com/3251469/44324553-4e252500-a456-11e8-956c-9790a18745a9.png">

**Comment by lidiamcfreitas** [comment]
Looking at the cities repository one can see that all the other cities were automatically updated in a previous commit 3 days ago, but not Zurich that was only updated 5 months ago.
<img width="1022" alt="screenshot 2018-08-20 08 55 39" src="https://user-images.githubusercontent.com/3251469/44324808-0eab0880-a457-11e8-924b-ff94e6fba53b.png">

**Comment by stefanw** [comment]
Mapnificent Zurich has been removed in favour of [Mapnificent Switzerland](https://www.mapnificent.net/switzerland/#12/47.3717/8.5423/900/47.3717/8.5423). A redirect has been put in place.

**Comment by lidiamcfreitas** [comment]
Thanks!
