### ISSUE TITLE
unreachable poins in the middle of the town

### ISSUE THREAD

**Issue by toolking** [mapnificent/mapnificent#28]
Some points are unreachable.
Example:
https://www.mapnificent.net/berlin/#13/52.4771/13.5446/5400/52.4689/13.5360
In 90 minutes normaly I can walk further than the shown range.

**Comment by stefanw** [comment]
The UI is very accurate for this. There's a total maximum walk time of 15 minutes that can be used up over your journey, here it's used right at the beginning. This should be explained better.

**Comment by toolking** [comment]
OK I understand. Points with more than 15minutes away from the next public transport stop are unreachable.
