### ISSUE TITLE
GTFS to JSON

### ISSUE THREAD

**Issue by maaslo** [mapnificent/mapnificent#3]
Hi, which tool should I use to create json from GTFS file?

**Comment by stefanw** [comment]
I'm still working on an improved version of this tool, not ready for the public yet. If you point me to a GTFS file, I can do the conversion.

**Comment by Hello1024** [comment]
Could you convert this file please?:
https://groups.google.com/forum/#!topic/transit-developers/rPY-bLuz4Tk

You may also want to include that file as part of your UK cities (London and Greater Manchester), but removing all stops that are outside the city boundaries.

**Comment by Hello1024** [comment]
(or maybe this one, which looks fresher: http://www.gbrail.info/gtfs.zip)

**Comment by Wilzi** [comment]
+1 for this feature

**Comment by sh4ring4n** [comment]
Until then, Can you convert this file too? [Here](http://www.citywindsor.ca/opendata/Lists/OpenData/Attachments/34/gtfs.zip)

**Comment by Wilzi** [comment]
Could you please convert me [this](http://gtfs.s3.amazonaws.com/bkk_20151009_0124.zip) gtfs file? Thanks!

**Comment by maaslo** [comment]
Hi, I tried to use your [generator] (https://github.com/mapnificent/mapnificent_generator) on [this] (http://www.infoprovsechny.cz/request/4355/response/6433/attach/3/Google%2020150729.rar) GTFS of Prague. I managed to export to JSON instead of protobuf, but it's structure still differs from yours. I Could you please take a look at that GTFS archive.

**Comment by davidjirovec** [comment]
@maaslo were you able to import Prague and make it work?

**Comment by hansthompson** [comment]
Please would you add this GTFS feed as well?

**Comment by botondbotos** [comment]
Could you add GTFS for Budapest?
http://www.bkk.hu/gtfs/budapest_gtfs.zip

**Comment by amarchen** [comment]
Hi @stefanw , could you possibly show even an old version of a tool?
I found a surprisingly up to date (as they claim) GTFS data for Saint-Petersburg at http://transport.orgp.spb.ru/Portal/transport/internalapi/gtfs and would love to play with it in mapnificent.

**Comment by Gyebro** [comment]
+1 for adding Budapest to Mapnificent. It used to have that city long ago... what happened?

**Comment by nikolauskrismer** [comment]
It would be great to publich the tool used for conversion, since:
* People could help out with the "add city XYZ" issues.
* It would be much easier to compare tools trying to achieve something similar (like my PhD project or the one mentioned in #7) to mapnificent.

**Comment by stefanw** [comment]
@nikolauskrismer The tool to generate the city data in the new protobuf format is here: https://github.com/mapnificent/mapnificent_generator

Starting mid August I will have some time to work on Mapnificent. Looking forward to it!

**Comment by nikolauskrismer** [comment]
That's great news (I did not find the repo by myself, sry).
Thanks a lot for that +1 :-)

**Comment by nateguy** [comment]
@stefanw Hello, I am trying to generate my own json file for this. Can you describe the steps needed to run this tool? Thanks!

**Comment by aghafoor** [comment]
@stefanw Hi Stefan, hope you are well and thank you for building such a great tool. 
I have been trying to get your script to work as well but no luck. I keep getting an empty JSON file regardless of which GTFS file I use, I have tried many.
Any chance you can issue some instructions on how to use it? 
https://github.com/mapnificent/mapnificent_generator

**Comment by aghafoor** [comment]
@nikolauskrismer Did you manage to get this JSON generator working? if yes - any chance you can help us with a single GTFS file?

**Comment by nikolauskrismer** [comment]
I could not use the mapnificent_creator project right now (since to import from code.google.com), but that might be also due to the fact that I am not very familiar with the go language.

What did you try right now?
How could you even create "an empty output"?

**Comment by aghafoor** [comment]
@nikolauskrismer thanks for taking the time to respond. We couldn't get the GO script to work so rewrote the code to use our own proprietary format json. Gave up the GO script.

**Comment by stefanw** [comment]
Hey everyone, I had some time to work on Mapnificent.

- (The Mapnificent Generator)[https://github.com/mapnificent/mapnificent_generator] is now mostly working. I'm also [providing binaries for Linux and OS X in the v0.0.1 release](https://github.com/mapnificent/mapnificent_generator/releases/tag/v0.0.1)
- The next version of Mapnificent using Protocol Buffers is available as a preview here: https://piano-tuner-bat-32317.netlify.com/
- READMEs have been updated all around.
- If you want to add a city, please follow the [description in the README of the Mapnificent Cities Repository](https://github.com/mapnificent/mapnificent_cities/blob/master/README.md)

Closing this now, because GTFS to JSON is now longer supported.
