### ISSUE TITLE
Amsterdam metro only in one direction

### ISSUE THREAD

**Issue by VincentSC** [mapnificent/mapnificent#30]
For Amsterdam the metro works clock-wise, but not counter-clockwise. This makes it look like the places in the East can reach far more of Amsterdam than the places in the West.

**Comment by stefanw** [comment]
Thanks for the report. Could you provide a screenshot that describes the problem so I can see when I fix it? I also need to verify if it's a data problem or a processing problem.

**Comment by VincentSC** [comment]
Thanks for the quick reply! I picked two stations that are 3 stops apart, so I could have a lower time to show it. 

10 minutes from metro "Heemstedestraat" does not bring you to "Zuid"  
![Metro-Heemstedestraat](https://user-images.githubusercontent.com/5090382/64650616-ea361b80-d41f-11e9-91f7-b835e5d01aff.PNG)
10 minutes from "Zuid" *does* bring you to metro "Heemstedestraat"  
![Metro-Zuid](https://user-images.githubusercontent.com/5090382/64650617-ea361b80-d41f-11e9-94bf-51a5c03803ec.PNG)

**Comment by VincentSC** [comment]
There seem to be more problems with handling openov-data: it does not check transfers, even not in the same transport type. For example it checks foot-train-foot, but not foot-train-train-foot. New issue?

**Comment by stefanw** [comment]
There's a limit on walking time per travel: currently max 15 minutes of walking. That could explain it.
You can also share links which will include selected positions and times.

**Comment by stefanw** [comment]
I just updated the data for the Netherlands. This seems to have fixed this particular issue:

https://www.mapnificent.net/netherlands/#14/52.3543/4.8633/600/52.3524/4.8346

Do you agree?

**Comment by VincentSC** [comment]
Yes!! I checked about 5 or 6 places I know well and it indeed is as I remember from experience (with the known limits of the current version, like walking over water and through buildings). Keep up the good work! 

You owe me one
