### ISSUE TITLE
javascript error on Sydney page

### ISSUE THREAD

**Issue by mlandauer** [mapnificent/mapnificent#5]
On the page http://www.mapnificent.net/sydney/

get in the console: `Uncaught RangeError: Maximum call stack size exceeded`

Would be so exciting to see mapnificent working for Sydney ;-)

**Comment by mlandauer** [comment]
It's all working now. Thanks!

**Comment by stefanw** [comment]
I increased the Quadtree leaf node capacity. Need to rewrite/replace the implementation at some point.
