### ISSUE TITLE
Add Vienna

### ISSUE THREAD

**Issue by logological** [mapnificent/mapnificent#8]
Any chance of adding support for Vienna?  The city maintains an [Open Data Portal](http://data.wien.gv.at/) that seems to include [an API and data for Wiener Linien, the public transit network](https://www.data.gv.at/katalog/dataset/9c203fec-dc0d-412c-a7a3-7fd77d0346f1).

**Comment by stefanw** [comment]
Vienna has been added to the Mapnificent cities repo in https://github.com/mapnificent/mapnificent_cities/pull/9. It will go live soon.
